package com.maxi3.dao2;

import com.maxi3.pojo2.TSample;
import java.util.List;

public interface TSampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sample
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    int deleteByPrimaryKey(Long sampleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sample
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    int insert(TSample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sample
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    TSample selectByPrimaryKey(Long sampleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sample
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    List<TSample> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sample
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    int updateByPrimaryKey(TSample record);
}