package com.maxi3.pojo2;

public class TSample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_ID
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private Long sampleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_DES
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private String sampleDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_DATE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private String sampleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.VERSION
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_TIL
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private String sampleTil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_CAMLEN
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private String sampleCamlen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_STAGE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private String sampleStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sample.SAMPLE_PIC
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    private byte[] samplePic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_ID
     *
     * @return the value of t_sample.SAMPLE_ID
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public Long getSampleId() {
        return sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_ID
     *
     * @param sampleId the value for t_sample.SAMPLE_ID
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleId(Long sampleId) {
        this.sampleId = sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_DES
     *
     * @return the value of t_sample.SAMPLE_DES
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public String getSampleDes() {
        return sampleDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_DES
     *
     * @param sampleDes the value for t_sample.SAMPLE_DES
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleDes(String sampleDes) {
        this.sampleDes = sampleDes == null ? null : sampleDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_DATE
     *
     * @return the value of t_sample.SAMPLE_DATE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public String getSampleDate() {
        return sampleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_DATE
     *
     * @param sampleDate the value for t_sample.SAMPLE_DATE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleDate(String sampleDate) {
        this.sampleDate = sampleDate == null ? null : sampleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.VERSION
     *
     * @return the value of t_sample.VERSION
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.VERSION
     *
     * @param version the value for t_sample.VERSION
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_TIL
     *
     * @return the value of t_sample.SAMPLE_TIL
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public String getSampleTil() {
        return sampleTil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_TIL
     *
     * @param sampleTil the value for t_sample.SAMPLE_TIL
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleTil(String sampleTil) {
        this.sampleTil = sampleTil == null ? null : sampleTil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_CAMLEN
     *
     * @return the value of t_sample.SAMPLE_CAMLEN
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public String getSampleCamlen() {
        return sampleCamlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_CAMLEN
     *
     * @param sampleCamlen the value for t_sample.SAMPLE_CAMLEN
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleCamlen(String sampleCamlen) {
        this.sampleCamlen = sampleCamlen == null ? null : sampleCamlen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_STAGE
     *
     * @return the value of t_sample.SAMPLE_STAGE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public String getSampleStage() {
        return sampleStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_STAGE
     *
     * @param sampleStage the value for t_sample.SAMPLE_STAGE
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSampleStage(String sampleStage) {
        this.sampleStage = sampleStage == null ? null : sampleStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sample.SAMPLE_PIC
     *
     * @return the value of t_sample.SAMPLE_PIC
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public byte[] getSamplePic() {
        return samplePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sample.SAMPLE_PIC
     *
     * @param samplePic the value for t_sample.SAMPLE_PIC
     *
     * @mbg.generated Tue Feb 20 15:20:06 GMT 2018
     */
    public void setSamplePic(byte[] samplePic) {
        this.samplePic = samplePic;
    }
}