/*     */ package com.maxi3.pojo;

public class TOutput {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.OUTPUT_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private Long outputId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.OUTPUT_DES
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private String outputDes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.OUTPUT_DATE
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private String outputDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.VERSION
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private Long version;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.SAMPLE_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private Long sampleId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.OUTPUT_EXPOSURETIME
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private String outputExposuretime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_output.OUTPUT_PIC
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	private byte[] outputPic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.OUTPUT_ID
	 *
	 * @return the value of t_output.OUTPUT_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public Long getOutputId() {
		return outputId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.OUTPUT_ID
	 *
	 * @param outputId
	 *            the value for t_output.OUTPUT_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setOutputId(Long outputId) {
		this.outputId = outputId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.OUTPUT_DES
	 *
	 * @return the value of t_output.OUTPUT_DES
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public String getOutputDes() {
		return outputDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.OUTPUT_DES
	 *
	 * @param outputDes
	 *            the value for t_output.OUTPUT_DES
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setOutputDes(String outputDes) {
		this.outputDes = outputDes == null ? null : outputDes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.OUTPUT_DATE
	 *
	 * @return the value of t_output.OUTPUT_DATE
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public String getOutputDate() {
		return outputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.OUTPUT_DATE
	 *
	 * @param outputDate
	 *            the value for t_output.OUTPUT_DATE
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setOutputDate(String outputDate) {
		this.outputDate = outputDate == null ? null : outputDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.VERSION
	 *
	 * @return the value of t_output.VERSION
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public Long getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.VERSION
	 *
	 * @param version
	 *            the value for t_output.VERSION
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setVersion(Long version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.SAMPLE_ID
	 *
	 * @return the value of t_output.SAMPLE_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public Long getSampleId() {
		return sampleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.SAMPLE_ID
	 *
	 * @param sampleId
	 *            the value for t_output.SAMPLE_ID
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setSampleId(Long sampleId) {
		this.sampleId = sampleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.OUTPUT_EXPOSURETIME
	 *
	 * @return the value of t_output.OUTPUT_EXPOSURETIME
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public String getOutputExposuretime() {
		return outputExposuretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.OUTPUT_EXPOSURETIME
	 *
	 * @param outputExposuretime
	 *            the value for t_output.OUTPUT_EXPOSURETIME
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setOutputExposuretime(String outputExposuretime) {
		this.outputExposuretime = outputExposuretime == null ? null : outputExposuretime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_output.OUTPUT_PIC
	 *
	 * @return the value of t_output.OUTPUT_PIC
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public byte[] getOutputPic() {
		return outputPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_output.OUTPUT_PIC
	 *
	 * @param outputPic
	 *            the value for t_output.OUTPUT_PIC
	 *
	 * @mbg.generated Thu Feb 08 21:24:18 GMT 2018
	 */
	public void setOutputPic(byte[] outputPic) {
		this.outputPic = outputPic;
	}
}